global:
  scrape_interval: 60s
  external_labels:
    monitor: 'railway-prom'

remote_write:
  - url: https://prometheus-prod-36-prod-us-west-0.grafana.net/api/prom/push
    basic_auth:
      username: ${GRAFANA_USERNAME}
      password: ${GRAFANA_PASSWORD}

scrape_configs:
  - job_name: 'node'
    static_configs:
      - targets: ['localhost:9090']
  
  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9090']
  
  - job_name: 'aegis'
    scrape_interval: 5s
    static_configs:
      - targets: ['${AEGIS}:${AEGIS_PORT}']
  